services:
  # Backend API service
  - type: web
    name: blogsite-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://amitkumarchowdary2004:Amit%40mongodb123@projects.zjefg.mongodb.net/
      - key: PORT
        value: 5000

  # Frontend static site
  - type: web
    name: blogsite-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
